import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Pricing Next App',
    description: 'Generated by create next app VC'
}

const PrincingPage = () => {
  return (
    <div>Princing Page</div>
  )
}

export default PrincingPage