import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Contact Next App',
    description: 'Generated by create next app VC'
}

export default function ContactPage() {
    return (
        <div>Contact Page</div>
    )
}
