import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'About Next App',
    description: 'Generated by create next app VC',
    keywords: ['About Page', 'Victor Clerque']
}

export default function AboutPage() {
    return (
        <span className='text-7xl'>About Page</span>
    )
}